# Generated by Django 5.0 on 2023-12-28 15:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Enter your character's name", max_length=20)),
                ('race', models.CharField(choices=[('HMN', 'Human'), ('DWF', 'Dwarf'), ('ELF', 'Elf'), ('HEF', 'Half Elf'), ('DRB', 'Dragonborn'), ('GNM', 'Gnome'), ('HOR', 'HOR'), ('TFG', 'Tiefling')], max_length=20)),
                ('character_class', models.CharField(choices=[('ART', 'ART'), ('BAR', 'BAR'), ('BAR', 'BAR'), ('CLR', 'CLR'), ('DRD', 'DRD'), ('FGT', 'FGT'), ('MNK', 'MNK'), ('PLD', 'PLD'), ('RNG', 'RNG'), ('ROG', 'ROG'), ('SRC', 'SRC'), ('WRC', 'WRC'), ('WZD', 'WZD')], max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('experience_points', models.IntegerField(default=0)),
                ('hp', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_hp', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('strength', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dexterity', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('constitution', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('intelligence', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('wisdom', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('charisma', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('story1', models.CharField(help_text='What is your story?', max_length=1000)),
                ('story2', models.CharField(help_text='What is your story?', max_length=1000)),
                ('story3', models.CharField(help_text='What is your story?', max_length=1000)),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
