# Generated by Django 5.0 on 2024-01-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnd_zero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(choices=[('ART', 'Artificer'), ('BAR', 'Barbarian'), ('BAR', 'Bard'), ('CLR', 'Cleric'), ('DRD', 'Druid'), ('FGT', 'Fighter'), ('MNK', 'Monk'), ('PLD', 'Paladin'), ('RNG', 'Ranger'), ('ROG', 'Rogue'), ('SRC', 'Sorcerer'), ('WRC', 'Warlock'), ('WZD', 'Wizard')], max_length=20),
        ),
    ]
